### ISSUE TITLE
Error compiling 'libblas'

### ISSUE THREAD

**Issue by Lyuu17** [xiaomi-sdm660/android_device_xiaomi_sdm660-common#34]
I get this error while compiling: https://del.dog/elikexavaz

I have all trees and it seems a tree issue, not a ROM one

**Comment by rcstar6696** [comment]
Your ccache is broken. Remove it and downgrade ccache package. 

This is not related to the tree

**Comment by Lyuu17** [comment]
ok thanks, i removed ccache package and now it builds without any issue
