### ISSUE TITLE
error loading camera hal

### ISSUE THREAD

**Issue by quesoo** [xiaomi-sdm660/android_device_xiaomi_sdm660-common#43]
https://github.com/xiaomi-sdm660/android_device_xiaomi_sdm660-common/blob/b504a81314a8687db8b8e0c109ae76e9c64ce039/proprietary-files.txt#L650

03-29 22:31:40.699 25481 25481 E mm-camera: <IMGLIB><ERROR> 1348: frameproc_comp_reload_lib: Error opening frameproc library libmmcamera_llvd.so error dlopen failed: cannot locate symbol "_ZN14SeeMoreWrapper11_yu3oaTHCJgEv" referenced by "/vendor/lib/libllvd_smore.so"...

any suggestion how to fix this?

**Comment by rcstar6696** [comment]
Shim it but its unneded as cam works without and stock rom not even has the lib
Its from somewhere else i do not mention here

**Comment by quesoo** [comment]
do you have any idea what is calling those libs?

# Common Camera
vendor/lib/libchromaflash.so|cf85560822e04014b8950a1abae9c2843069101d
vendor/lib/libllvd_smore.so|740de4c339772df80858ddd9390f91ead71eadeb
vendor/lib/libmmcamera_chromaflash_lib.so|2ac15c08e7916b039b9d053a2d5c6846ed28ae41
vendor/lib/libmmcamera_llvd.so|6fca05767e27b9a5f0050fc9296069c09e9f5dba
vendor/lib/libmmcamera_optizoom_lib.so|0d54dcba2f86236b66384aa83861693451ee0451
vendor/lib/libmmcamera_stillmore_lib.so|72ddda5608ee9f2d14f3e7321c992c3aa3dbdcf7
vendor/lib/libmmcamera_trueportrait_lib.so|41f491298caf7ddd2fd19b9f71906fd9f2a826ff
vendor/lib/libmmcamera_ubifocus_lib.so|204680decba87b04a2eb5ad4746e69f8e0c413bc
vendor/lib/liboptizoom.so|1e92993743636c045438f1f15c07c1e835d9ca46
vendor/lib/libseemore.so|cd207541c3cdd97eb25ef2a9c63662054393e81f
vendor/lib/libtrueportrait.so|b8e11c098bd859aae6c535cdb87e3e36f6b1c6ef
vendor/lib/libubifocus.so|833a305c780b2e7e338323c5ba27cb042f5cc3ed

for me (xiaomi jason) those where not needed on pie

**Comment by rcstar6696** [comment]
Even in ten it works without. Those libs are all qcom camera hal libs and deps of the hal by default but not fatal erroing if not there. I noticed just a slightly diffrence in quality but not really worth.

**Comment by quesoo** [comment]
It was related to oss version of libminikin.
Prebuilt Pie libminikin fixed this and makes them unnessecary. Thanks for all help
