### ISSUE TITLE
Sepolicy is broken. Contains duplicates

### ISSUE THREAD

**Issue by verNANDo57** [xiaomi-sdm660/android_device_xiaomi_sdm660-common#57]
Sepolicy is broken. Contains duplicates:
________
sepolicy/vendor/genfs_contexts: 
...
# Battery
genfscon sysfs /devices/soc/c176000.i2c/i2c-2/2-001d            u:object_r:sysfs_battery_supply:s0
...
# Camera
genfscon sysfs /devices/soc/ca0c000.qcom,cci/ca0c000.qcom,cci:qcom,camera@3/video4linux/video5/name                                     u:object_r:sysfs_graphics:s0
________

Using this tree leads to system process crash and many other errors
Tested on CarbonRom and AEX

**Comment by verNANDo57** [comment]
Rom's problem

**Comment by rcstar6696** [comment]
All works fine here i build official carbon with that tree
